/*
 * inject-api-key.js — dev convenience only.
 *
 * Runs under real Node on the host machine (unlike src/pkjs, which runs in
 * the phone's JS runtime and has no `process.env`). Reads TRANSIT_511_API_TOKEN
 * from .env and writes it into src/pkjs/localSecrets.js, a git-ignored file
 * that index.js requires as a fallback default for the Clay "ApiKey" field.
 *
 * Run this after editing .env, before `pebble build`:
 *   node scripts/inject-api-key.js
 */

var fs = require("fs");
var path = require("path");

var root = path.join(__dirname, "..");
var envPath = path.join(root, ".env");
var outPath = path.join(root, "src", "pkjs", "localSecrets.js");

function parseEnvFile(text) {
  var vars = {};
  text.split("\n").forEach(function (line) {
    var trimmed = line.trim();
    if (!trimmed || trimmed.indexOf("#") === 0) return;
    var eq = trimmed.indexOf("=");
    if (eq === -1) return;
    var key = trimmed.slice(0, eq).trim();
    var value = trimmed.slice(eq + 1).trim();
    // Strip matching surrounding quotes, if any.
    if (
      value.length >= 2 &&
      (value[0] === '"' || value[0] === "'") &&
      value[value.length - 1] === value[0]
    ) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  });
  return vars;
}

var apiKey = "";
if (fs.existsSync(envPath)) {
  var parsed = parseEnvFile(fs.readFileSync(envPath, "utf8"));
  apiKey = parsed.TRANSIT_511_API_TOKEN || "";
}

fs.writeFileSync(
  outPath,
  "// Auto-generated by scripts/inject-api-key.js — do not edit, do not commit.\n" +
    "module.exports = " + JSON.stringify({ apiKey: apiKey }, null, 2) + ";\n"
);

console.log(
  apiKey
    ? "localSecrets.js written with API key from .env"
    : "localSecrets.js written with an empty API key (.env missing or TRANSIT_511_API_TOKEN unset)"
);
